### correct Mijnden -----------------------------------------------------
# 1: 3-34, 2: 35-50, 3:69-82, 4: 51-68, 5: 83-98, 6: 99-122, 123:154, 155:183, 184:215, 216:246,280:314, 247:279,  315:350, 351:386,387:429, 430:471
setDT(profiel)
profiel[,ID := as.numeric(ID)]
profiel[name == 'polder mijnden zuid' & Puntnummer >= 3 & Puntnummer <= 34, ID := paste0(ID,'.',1) ]
profiel[name == 'polder mijnden zuid' & Puntnummer >= 35 & Puntnummer <= 50, ID := paste0(ID,'.',2) ]
profiel[name == 'polder mijnden zuid' & Puntnummer >= 51 & Puntnummer <= 68, ID := paste0(ID,'.',3) ]
profiel[name == 'polder mijnden zuid' & Puntnummer >= 69 & Puntnummer <= 82, ID := paste0(ID,'.',4) ]
profiel[name == 'polder mijnden zuid' & Puntnummer >= 83 & Puntnummer <= 98, ID := paste0(ID,'.',5) ]
profiel[name == 'polder mijnden zuid' & Puntnummer >= 99 & Puntnummer <= 122, ID := paste0(ID,'.',6) ]
profiel[name == 'polder mijnden zuid' & Puntnummer >= 123 & Puntnummer <= 154, ID := paste0(ID,'.',7) ]
profiel[name == 'polder mijnden zuid' & Puntnummer >= 155 & Puntnummer <= 183, ID := paste0(ID,'.',8) ]
profiel[name == 'polder mijnden zuid' & Puntnummer >= 184 & Puntnummer <= 215, ID := paste0(ID,'.',9) ]
profiel[name == 'polder mijnden zuid' & Puntnummer >= 216 & Puntnummer <= 246, ID := paste0(ID,'.',11) ]
profiel[name == 'polder mijnden zuid' & Puntnummer >= 247 & Puntnummer <= 279, ID := paste0(ID,'.',12) ]
profiel[name == 'polder mijnden zuid' & Puntnummer >= 280 & Puntnummer <= 314, ID := paste0(ID,'.',13) ]
profiel[name == 'polder mijnden zuid' & Puntnummer >= 315 & Puntnummer <= 350, ID := paste0(ID,'.',14) ]
profiel[name == 'polder mijnden zuid' & Puntnummer >= 351 & Puntnummer <= 386, ID := paste0(ID,'.',15) ]
profiel[name == 'polder mijnden zuid' & Puntnummer >= 387 & Puntnummer <= 429, ID := paste0(ID,'.',16) ]
profiel[name == 'polder mijnden zuid' & Puntnummer >= 430 & Puntnummer <= 471, ID := paste0(ID,'.',17) ]
profiel[name == 'polder mijnden zuid' & Puntnummer == 3 , Puntnummer := 1 ]
profiel[name == 'polder mijnden zuid' & Puntnummer == 35 , Puntnummer := 1 ]
profiel[name == 'polder mijnden zuid' & Puntnummer == 51 , Puntnummer := 1 ]
profiel[name == 'polder mijnden zuid' & Puntnummer == 69 , Puntnummer := 1 ]
profiel[name == 'polder mijnden zuid' & Puntnummer == 83 , Puntnummer := 1 ]
profiel[name == 'polder mijnden zuid' & Puntnummer == 99 , Puntnummer := 1 ]
profiel[name == 'polder mijnden zuid' & Puntnummer == 123 , Puntnummer:= 1 ]
profiel[name == 'polder mijnden zuid' & Puntnummer == 155 , Puntnummer := 1 ]
profiel[name == 'polder mijnden zuid' & Puntnummer == 184 , Puntnummer := 1 ]
profiel[name == 'polder mijnden zuid' & Puntnummer == 216 , Puntnummer:= 1 ]
profiel[name == 'polder mijnden zuid' & Puntnummer == 247 , Puntnummer:= 1]
profiel[name == 'polder mijnden zuid' & Puntnummer == 280 , Puntnummer := 1]
profiel[name == 'polder mijnden zuid' & Puntnummer == 315 , Puntnummer:= 1 ]
profiel[name == 'polder mijnden zuid' & Puntnummer == 351 , Puntnummer:= 1 ]
profiel[name == 'polder mijnden zuid' & Puntnummer == 387 , Puntnummer:= 1 ]
profiel[name == 'polder mijnden zuid' & Puntnummer == 430 , Puntnummer:= 1]